In [30]:
import pandas as pd
from datetime import datetime

In [31]:
data = pd.read_excel('data/2022도로교량및터널현황조서.xls', sheet_name='2022_교량')

In [32]:
data.head()

,도로종류,노선명,시설명,시도,시군구,읍면동,리,총길이,총폭,유효폭,...,경간수,최대경간장,상부구조,하부구조,설계하중,교통량,기관구분1,기관구분2,기관구분3,준공년도
0,고속국도,고속국도12호선,88낙동강교(광주),대구광역시,달성군,논공읍,위천리,812.0,15.7,14.7,...,22.0,60.0,PSCI거더교,NaN,DB-24,17850.0,전문관리기관,한국도로공사,고령지사,1984
1,고속국도,고속국도12호선,88낙동강교(대구),대구광역시,달성군,논공읍,위천리,806.0,15.8,14.9,...,14.0,61.2,강박스거더교,NaN,DB-24,17850.0,전문관리기관,한국도로공사,고령지사,2006
2,고속국도,고속국도25호선,RAMP-A교,전라남도,장성군,남면,삼태리,90.0,13.9,13.0,...,2.0,45.0,PSCI거더교,역 T형식교대,DB-24,20998.0,자치단체,광주,시청,2015
3,고속국도,고속국도25호선,RAMP-H교,전라남도,장성군,남면,삼태리,55.0,7.9,7.0,...,1.0,55.0,강박스거더교,역 T형식교대,DB-24,20998.0,자치단체,광주,종합건설본부,2016
4,고속국도,고속국도25호선,RAMP-I교,전라남도,장성군,남면,삼태리,55.0,7.9,7.0,...,1.0,55.0,강박스거더교,역 T형식교대,DB-24,20998.0,자치단체,광주,종합건설본부,2016

In [33]:
data.columns

Index(['도로종류', '노선명', '시설명', '시도', '시군구', '읍면동', '리', '총길이', '총폭', '유효폭', '높이',
       '경간수', '최대경간장', '상부구조', '하부구조', '설계하중', '교통량', '기관구분1', '기관구분2',
       '기관구분3', '준공년도'],
      dtype='object')

In [34]:
# 필요없는 컬럼 제거
trash = ['도로종류', '노선명', '읍면동', '리', '유효폭', '높이', '하부구조', '기관구분1', '기관구분2', '기관구분3']
data = data.drop(trash, axis=1)
data.columns

Index(['시설명', '시도', '시군구', '총길이', '총폭', '경간수', '최대경간장', '상부구조', '설계하중', '교통량',
       '준공년도'],
      dtype='object')

In [35]:
unique_values = data['시도'].unique()
print(unique_values)

['대구광역시' '전라남도' '강원도' '충청남도' '전라북도' '경기도' '부산광역시' '충청북도' '경상북도' '경상남도'
 '대전광역시' '울산광역시' '서울특별시' '인천광역시' '광주광역시' '세종특별자치시' '제주특별자치도']

In [36]:
# 서울특별시, 경기도 데이터만 추출
data = data[data['시도'].isin(['서울특별시', '경기도'])]
unique_values = data['시도'].unique()
print(unique_values)
data.head()

['경기도' '서울특별시']

,시설명,시도,시군구,총길이,총폭,경간수,최대경간장,상부구조,설계하중,교통량,준공년도
17,가남JCT육교(강릉),경기도,여주군,225.0,16.2,5.0,45.0,강박스거더교,DB-24,24562.0,1994
18,가남JCT육교(인천),경기도,여주군,225.0,16.2,5.0,45.0,강박스거더교,DB-24,24562.0,1994
19,가남교(강릉0),경기도,여주군,25.0,19.3,1.0,25.0,프리플렉스거더교,DB-24,61826.0,2003
20,가남교(강릉1),경기도,여주군,25.0,5.6,1.0,25.0,PSCI거더교,DB-24,61826.0,2010
21,가남교(인천),경기도,여주군,25.0,19.3,1.0,25.0,프리플렉스거더교,DB-24,61826.0,2003

In [37]:
data.isnull().sum()

시설명         0
시도          0
시군구         0
총길이         0
총폭          2
경간수         0
최대경간장       0
상부구조        0
설계하중        0
교통량      2055
준공년도        0
dtype: int64

In [38]:
result = data.loc[data['총폭'].isnull()]
result

        시설명   시도      시군구    총길이  총폭  경간수  최대경간장 상부구조   설계하중  교통량  준공년도
28924   사암교  경기도  용인시 처인구   26.4 NaN  2.0   13.2  라멘교  DB-24  NaN  2001
32414  호장교2  경기도     의정부시  180.0 NaN  6.0   30.0   기타  DB-24  NaN  2014

In [39]:
result = data.loc[data['총폭'] == 0, ['시설명', '시도', '총길이', '총폭', '교통량', '상부구조', '준공년도']]
result

       시설명   시도   총길이   총폭      교통량      상부구조  준공년도
22739  가업교  경기도  35.0  0.0  12232.0  프리플렉스거더교  2014
26815  가목교  경기도  25.0  0.0      NaN       라멘교  1998

In [40]:
# 사암교, 호장교2, 가목교 제거
data = data[~data["시설명"].isin(["사암교", "호장교2", "가목교"])]
result = data[data['시설명'].isin(['사암교', '호장교2', '가목교'])]
result

Empty DataFrame
Columns: [시설명, 시도, 시군구, 총길이, 총폭, 경간수, 최대경간장, 상부구조, 설계하중, 교통량, 준공년도]
Index: []

In [41]:
# 가업교 제거
data = data.loc[~((data["준공년도"] == 2014) & (data["시설명"] == "가업교"))]

In [42]:
result = data.loc[data['준공년도'] == 8888, ['시설명', '시도', '총길이', '총폭', '교통량', '준공년도', '상부구조']]
result

          시설명   시도   총길이    총폭      교통량  준공년도     상부구조
21934     세월교  경기도  83.0   9.0   3352.0  8888       기타
23922     무명교  경기도  13.5  12.0  13254.0  8888      라멘교
24162    봉명소교  경기도   4.8   4.5   4595.0  8888      라멘교
25184     역북교  경기도  11.0  12.7   7204.0  8888      라멘교
26774  (구)추계교  경기도  15.0   7.5      NaN  8888      라멘교
26839     가장교  경기도  30.0   6.5      NaN  8888   RC슬래브교
27064    고산1교  경기도  10.4  10.2   5314.0  8888      라멘교
27381    궁평3교  경기도   8.0  13.5   3309.0  8888      라멘교
28433     무명교  경기도   6.4   5.0      NaN  8888      라멘교
29152    상림3교  경기도   6.7   9.6   3309.0  8888      라멘교
29797    식송1교  경기도  10.0   9.1      NaN  8888      라멘교
30343    연곡1교  경기도  12.0  13.0      0.0  8888  RC박스거더교
30652     용동교  경기도  18.6   9.0      NaN  8888      라멘교
31489    제청2교  경기도  10.0  10.9      0.0  8888      라멘교
31687    직동1교  경기도  10.4   8.9      0.0  8888      라멘교
31949     태전교  경기도  29.0  15.0  13215.0  8888      라멘교
32043     틀못교  경기도  10.4   6.0      0.0  8888   RC슬래브교
32103    평촌1교  경기도  12.4   9.5      NaN  8888      라멘교
32104    평촌2교  경기도  24.0   8.0      NaN  8888      라멘교
32105    평촌3교  경기도  16.0   5.5      NaN  8888      라멘교
34381   설매실1교  경기도   6.0   7.0      0.0  8888   RC슬래브교
34382   설매실2교  경기도   5.0   5.0      0.0  8888   RC슬래브교
34383   설매실3교  경기도   8.0   5.0      0.0  8888   RC슬래브교

In [43]:
data.loc[(data["시설명"] == "세월교") & (data["준공년도"] == 8888), "준공년도"] = 2010
data.loc[(data["시설명"] == "역북교") & (data["준공년도"] == 8888), "준공년도"] = 1995
data.loc[(data["시설명"] == "설매실1교") & (data["준공년도"] == 8888), "준공년도"] = 1980
data.loc[(data["시설명"] == "설매실2교") & (data["준공년도"] == 8888), "준공년도"] = 2018

In [44]:
result = data.loc[data['시설명'].isin(['세월교', '역북교', '설매실1교', '설매실2교']), ['시설명', '시도', '총길이', '총폭', '설계하중','교통량', '상부구조', '준공년도']]
result

         시설명   시도   총길이    총폭     설계하중     교통량    상부구조  준공년도
21934    세월교  경기도  83.0   9.0       미상  3352.0      기타  2010
21935    세월교  경기도  30.0  14.0    DB-24  7242.0     라멘교  1999
24674    세월교  경기도  20.0   7.9    DB-24     NaN     라멘교  2009
25184    역북교  경기도  11.0  12.7    DB-24  7204.0     라멘교  1995
34381  설매실1교  경기도   6.0   7.0  DB-13.5     0.0  RC슬래브교  1980
34382  설매실2교  경기도   5.0   5.0  DB-13.5     0.0  RC슬래브교  2018
34434    세월교  경기도  30.0   6.9       기타     NaN  RCT거더교  1976

In [45]:
data = data.loc[data["준공년도"] != 8888]
unique_values = data['준공년도'].unique()
print(unique_values)

[1994 2003 2010 1999 2016 2011 2017 2008 1991 2002 2009 1987 2001 2000
 2013 1996 2012 1993 2006 2019 1992 2018 1968 1998 1997 2021 2015 1995
 1969 2014 2004 2005 1976 2007 1988 1986 1963 1960 1989 1961 1973 1985
 2020 1982 1990 1975 1971 1981 1983 1972 1978 1965 1979 1977 1984 1966
 1970 1980 1974 1967 1937 1964 1962 1959 1947 1954 1956 1940]

In [46]:
# 준공년도를 준공후경과년수로 변환
data['준공후경과년수'] = datetime.today().year - data.loc[:, '준공년도']
data.head()

,시설명,시도,시군구,총길이,총폭,경간수,최대경간장,상부구조,설계하중,교통량,준공년도,준공후경과년수
17,가남JCT육교(강릉),경기도,여주군,225.0,16.2,5.0,45.0,강박스거더교,DB-24,24562.0,1994,29
18,가남JCT육교(인천),경기도,여주군,225.0,16.2,5.0,45.0,강박스거더교,DB-24,24562.0,1994,29
19,가남교(강릉0),경기도,여주군,25.0,19.3,1.0,25.0,프리플렉스거더교,DB-24,61826.0,2003,20
20,가남교(강릉1),경기도,여주군,25.0,5.6,1.0,25.0,PSCI거더교,DB-24,61826.0,2010,13
21,가남교(인천),경기도,여주군,25.0,19.3,1.0,25.0,프리플렉스거더교,DB-24,61826.0,2003,20

In [47]:
result = data.loc[data['경간수'] == 0, ['시설명', '시도', '총길이', '총폭', '교통량', '상부구조']]
result

          시설명     시도   총길이    총폭  교통량     상부구조
20502  신정교접속교  서울특별시  68.0   8.0  NaN  PSCI거더교
20582    여의천교  서울특별시  70.0  25.9  NaN       기타
20634  오금교접속교  서울특별시  60.0  29.5  NaN      라멘교

In [48]:
data = data.loc[data["경간수"] != 0]

In [49]:
result = data.loc[data['경간수'] == 0, ['시설명', '시도', '총길이', '총폭', '교통량', '상부구조']]
result

Empty DataFrame
Columns: [시설명, 시도, 총길이, 총폭, 교통량, 상부구조]
Index: []

In [50]:
unique_values = data['설계하중'].unique()
print(unique_values)

['DB-24' '기타' 'DB-18' 'DB-13.5' 'DB-24(성능개선)' '미상' 'DB-9' 'T13 또는 D13'
 'T9 또는 D9']

In [51]:
data.loc[data['설계하중'] == 'DB-24(성능개선)', '설계하중'] = 'DB-24'

In [52]:
unique_values = data['설계하중'].unique()
print(unique_values)

['DB-24' '기타' 'DB-18' 'DB-13.5' '미상' 'DB-9' 'T13 또는 D13' 'T9 또는 D9']

In [53]:
# 인덱스 재정렬
data = data.reset_index(drop=True)
data.head()

,시설명,시도,시군구,총길이,총폭,경간수,최대경간장,상부구조,설계하중,교통량,준공년도,준공후경과년수
0,가남JCT육교(강릉),경기도,여주군,225.0,16.2,5.0,45.0,강박스거더교,DB-24,24562.0,1994,29
1,가남JCT육교(인천),경기도,여주군,225.0,16.2,5.0,45.0,강박스거더교,DB-24,24562.0,1994,29
2,가남교(강릉0),경기도,여주군,25.0,19.3,1.0,25.0,프리플렉스거더교,DB-24,61826.0,2003,20
3,가남교(강릉1),경기도,여주군,25.0,5.6,1.0,25.0,PSCI거더교,DB-24,61826.0,2010,13
4,가남교(인천),경기도,여주군,25.0,19.3,1.0,25.0,프리플렉스거더교,DB-24,61826.0,2003,20

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7373 entries, 0 to 7372
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   시설명      7373 non-null   object
 1   시도       7373 non-null   object
 2   시군구      7373 non-null   object
 3   총길이      7373 non-null   float64
 4   총폭       7373 non-null   float64
 5   경간수      7373 non-null   float64
 6   최대경간장    7373 non-null   float64
 7   상부구조     7373 non-null   object
 8   설계하중     7373 non-null   object
 9   교통량      5333 non-null   float64
 10  준공년도     7373 non-null   int64
 11  준공후경과년수  7373 non-null   int64
dtypes: float64(5), int64(2), object(5)
memory usage: 691.3+ KB

In [55]:
data.to_csv("data/2022도로교량현황조서_정제.csv", encoding='utf-8-sig', index=False)