In [29]:
import pandas as pd

# **서울**

### 시군구별 최종안전점검결과/준공후경과년수 평균

In [30]:
seoul = pd.read_csv('data/s_map_data.csv')
seoul.tail(3)

       교량명 시군구명 최종안전점검결과  준공후경과년수 시설물종별등급구분    교량시작점위도     교량시작점경도
433  무지개다리  송파구        B       37         3  37.525180  127.123654
434    청룡교  송파구        B       37         3  37.522898  127.127324
435   공대교량  관악구        B       49         3  37.456052  126.949550

In [31]:
# 안전등급 매핑 딕셔너리 생성
safety_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5}
seoul['safty'] = seoul['최종안전점검결과'].map(safety_map)
seoul

,교량명,시군구명,최종안전점검결과,준공후경과년수,시설물종별등급구분,교량시작점위도,교량시작점경도,safty
0,잠수교,용산구,B,47,1,37.511568,126.998013,2
1,장월교,노원구,C,32,3,37.617827,127.056945,3
2,안양천교,강서구,C,40,3,37.554427,126.875821,3
3,탄천교,강남구,B,37,3,37.518430,127.066870,2
4,난지교,마포구,B,30,3,37.575906,126.861259,2
...,...,...,...,...,...,...,...,...
431,"국제선 제2고가도로(2,5,6,) 램프구간",강서구,B,12,3,37.565840,126.804340,2
432,구중교,송파구,B,38,3,37.523978,127.117163,2
433,무지개다리,송파구,B,37,3,37.525180,127.123654,2
434,청룡교,송파구,B,37,3,37.522898,127.127324,2
435,공대교량,관악구,B,49,3,37.456052,126.949550,2

In [32]:
s = seoul[['교량명', '시군구명', '최종안전점검결과','safty', '준공후경과년수', '시설물종별등급구분', '교량시작점위도', '교량시작점경도']]
s

,교량명,시군구명,최종안전점검결과,safty,준공후경과년수,시설물종별등급구분,교량시작점위도,교량시작점경도
0,잠수교,용산구,B,2,47,1,37.511568,126.998013
1,장월교,노원구,C,3,32,3,37.617827,127.056945
2,안양천교,강서구,C,3,40,3,37.554427,126.875821
3,탄천교,강남구,B,2,37,3,37.518430,127.066870
4,난지교,마포구,B,2,30,3,37.575906,126.861259
...,...,...,...,...,...,...,...,...
431,"국제선 제2고가도로(2,5,6,) 램프구간",강서구,B,2,12,3,37.565840,126.804340
432,구중교,송파구,B,2,38,3,37.523978,127.117163
433,무지개다리,송파구,B,2,37,3,37.525180,127.123654
434,청룡교,송파구,B,2,37,3,37.522898,127.127324
435,공대교량,관악구,B,2,49,3,37.456052,126.949550

In [33]:
# 시군구코드 추가
local_code = {'강남구':11680, '강동구':11740, '강북구':11305, '강서구':11500, '관악구':11620,
              '광진구':11215, '구로구':11530, '금천구':11545, '노원구':11350, '도봉구':11320, '동대문구':11230,
              '동작구':11590, '마포구':11440, '서대문구':11410, '서초구':11650, '성동구':11200, '성북구':11290,
              '송파구':11710, '양천구':11470, '영등포구':11560, '용산구':11170, '은평구':11380,  '종로구':11110,
              '중구':11140, '중랑구':11260}
s['id'] = s['시군구명'].map(local_code)
s

C:\Users\82109\AppData\Local\Temp\ipykernel_29516\2152549084.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s['id'] = s['시군구명'].map(local_code)

,교량명,시군구명,최종안전점검결과,safty,준공후경과년수,시설물종별등급구분,교량시작점위도,교량시작점경도,id
0,잠수교,용산구,B,2,47,1,37.511568,126.998013,11170
1,장월교,노원구,C,3,32,3,37.617827,127.056945,11350
2,안양천교,강서구,C,3,40,3,37.554427,126.875821,11500
3,탄천교,강남구,B,2,37,3,37.518430,127.066870,11680
4,난지교,마포구,B,2,30,3,37.575906,126.861259,11440
...,...,...,...,...,...,...,...,...,...
431,"국제선 제2고가도로(2,5,6,) 램프구간",강서구,B,2,12,3,37.565840,126.804340,11500
432,구중교,송파구,B,2,38,3,37.523978,127.117163,11710
433,무지개다리,송파구,B,2,37,3,37.525180,127.123654,11710
434,청룡교,송파구,B,2,37,3,37.522898,127.127324,11710
435,공대교량,관악구,B,2,49,3,37.456052,126.949550,11620

In [34]:
result = s.groupby('시군구명').agg({'safty': 'mean', '준공후경과년수': 'mean'}).reset_index()
result.columns = ['시군구명', 'mean_safty', 'mean_after']

# 시군구코드 추가
local_code = {'강남구':11680, '강동구':11740, '강북구':11305, '강서구':11500, '관악구':11620,
              '광진구':11215, '구로구':11530, '금천구':11545, '노원구':11350, '도봉구':11320, '동대문구':11230,
              '동작구':11590, '마포구':11440, '서대문구':11410, '서초구':11650, '성동구':11200, '성북구':11290,
              '송파구':11710, '양천구':11470, '영등포구':11560, '용산구':11170, '은평구':11380,  '종로구':11110,
              '중구':11140, '중랑구':11260}
result['id'] = result['시군구명'].map(local_code)

result['mean_safty'] = round(result['mean_safty'], 1)
result['mean_after'] = round(result['mean_after'], 1)
result = result[['시군구명', 'id', 'mean_safty', 'mean_after']]
result

    시군구명     id  mean_safty  mean_after
0    강남구  11680         2.2        25.9
1    강동구  11740         2.1        22.6
2    강북구  11305         1.9        22.9
3    강서구  11500         2.3        24.1
4    관악구  11620         2.6        43.2
5    광진구  11215         2.2        24.5
6    구로구  11530         3.0        27.7
7    금천구  11545         2.8        24.1
8    노원구  11350         2.2        31.9
9    도봉구  11320         2.0        24.5
10  동대문구  11230         2.0        40.8
11   동작구  11590         2.1        30.0
12   마포구  11440         2.1        31.6
13  서대문구  11410         2.2        45.0
14   서초구  11650         2.2        20.6
15   성동구  11200         2.5        25.7
16   성북구  11290         2.1        27.6
17   송파구  11710         2.1        27.4
18   양천구  11470         2.0        35.0
19  영등포구  11560         2.5        30.6
20   용산구  11170         2.4        37.5
21   은평구  11380         2.6        20.4
22   종로구  11110         2.0        20.9
23    중구  11140         2.2        37.4
24   중랑구  11260         2.3        19.5

In [35]:
# csv 파일로 저장
result.to_csv('data/s_r_mean.csv', encoding='utf-8-sig', index=False)

### 시군구별 위도/경도

In [36]:
# 경도 추가
local_long = {'강남구':127.0629852, '강동구':127.1470118, '강북구':127.011189, '강서구':126.822807, '관악구':126.9453372,
              '광진구':127.0857435, '구로구':126.8563006, '금천구':126.9008202, '노원구':127.0750347, '도봉구':127.0323688, '동대문구':127.0548481,
              '동작구':126.9516415, '마포구':126.90827, '서대문구':126.9390631, '서초구':127.0312203, '성동구':127.0410585, '성북구':127.0175795,
              '송파구':127.115295, '양천구':126.8554777, '영등포구':126.9101695, '용산구':126.979907, '은평구':126.9270229,  '종로구':126.9773213,
              '중구':126.9959681, '중랑구':127.0928803}
result['long'] = result['시군구명'].map(local_long)
result

    시군구명     id  mean_safty  mean_after        long
0    강남구  11680         2.2        25.9  127.062985
1    강동구  11740         2.1        22.6  127.147012
2    강북구  11305         1.9        22.9  127.011189
3    강서구  11500         2.3        24.1  126.822807
4    관악구  11620         2.6        43.2  126.945337
5    광진구  11215         2.2        24.5  127.085744
6    구로구  11530         3.0        27.7  126.856301
7    금천구  11545         2.8        24.1  126.900820
8    노원구  11350         2.2        31.9  127.075035
9    도봉구  11320         2.0        24.5  127.032369
10  동대문구  11230         2.0        40.8  127.054848
11   동작구  11590         2.1        30.0  126.951641
12   마포구  11440         2.1        31.6  126.908270
13  서대문구  11410         2.2        45.0  126.939063
14   서초구  11650         2.2        20.6  127.031220
15   성동구  11200         2.5        25.7  127.041059
16   성북구  11290         2.1        27.6  127.017579
17   송파구  11710         2.1        27.4  127.115295
18   양천구  11470         2.0        35.0  126.855478
19  영등포구  11560         2.5        30.6  126.910169
20   용산구  11170         2.4        37.5  126.979907
21   은평구  11380         2.6        20.4  126.927023
22   종로구  11110         2.0        20.9  126.977321
23    중구  11140         2.2        37.4  126.995968
24   중랑구  11260         2.3        19.5  127.092880

In [37]:
# 위도 추가
local_lat = {'강남구':37.49664389, '강동구':37.55045024, '강북구':37.64347391, '강서구':37.56123543, '관악구':37.46737569,
              '광진구':37.54670608, '구로구':37.49440543, '금천구':37.46056756, '노원구':37.65251105, '도봉구':37.66910208, '동대문구':37.58195655,
              '동작구':37.49887688, '마포구':37.55931349, '서대문구':37.57778531, '서초구':37.47329547, '성동구':37.55102969, '성북구':37.6057019,
              '송파구':37.50561924, '양천구':37.52478941, '영등포구':37.52230829, '용산구':37.53138497, '은평구':37.61921128,  '종로구':37.59491732,
              '중구':37.56014356, '중랑구':37.59780259}
result['lat'] = result['시군구명'].map(local_lat)
result

    시군구명     id  mean_safty  mean_after        long        lat
0    강남구  11680         2.2        25.9  127.062985  37.496644
1    강동구  11740         2.1        22.6  127.147012  37.550450
2    강북구  11305         1.9        22.9  127.011189  37.643474
3    강서구  11500         2.3        24.1  126.822807  37.561235
4    관악구  11620         2.6        43.2  126.945337  37.467376
5    광진구  11215         2.2        24.5  127.085744  37.546706
6    구로구  11530         3.0        27.7  126.856301  37.494405
7    금천구  11545         2.8        24.1  126.900820  37.460568
8    노원구  11350         2.2        31.9  127.075035  37.652511
9    도봉구  11320         2.0        24.5  127.032369  37.669102
10  동대문구  11230         2.0        40.8  127.054848  37.581957
11   동작구  11590         2.1        30.0  126.951641  37.498877
12   마포구  11440         2.1        31.6  126.908270  37.559313
13  서대문구  11410         2.2        45.0  126.939063  37.577785
14   서초구  11650         2.2        20.6  127.031220  37.473295
15   성동구  11200         2.5        25.7  127.041059  37.551030
16   성북구  11290         2.1        27.6  127.017579  37.605702
17   송파구  11710         2.1        27.4  127.115295  37.505619
18   양천구  11470         2.0        35.0  126.855478  37.524789
19  영등포구  11560         2.5        30.6  126.910169  37.522308
20   용산구  11170         2.4        37.5  126.979907  37.531385
21   은평구  11380         2.6        20.4  126.927023  37.619211
22   종로구  11110         2.0        20.9  126.977321  37.594917
23    중구  11140         2.2        37.4  126.995968  37.560144
24   중랑구  11260         2.3        19.5  127.092880  37.597803

In [38]:
result = result[['시군구명', 'id', 'long', 'lat']]
result

    시군구명     id        long        lat
0    강남구  11680  127.062985  37.496644
1    강동구  11740  127.147012  37.550450
2    강북구  11305  127.011189  37.643474
3    강서구  11500  126.822807  37.561235
4    관악구  11620  126.945337  37.467376
5    광진구  11215  127.085744  37.546706
6    구로구  11530  126.856301  37.494405
7    금천구  11545  126.900820  37.460568
8    노원구  11350  127.075035  37.652511
9    도봉구  11320  127.032369  37.669102
10  동대문구  11230  127.054848  37.581957
11   동작구  11590  126.951641  37.498877
12   마포구  11440  126.908270  37.559313
13  서대문구  11410  126.939063  37.577785
14   서초구  11650  127.031220  37.473295
15   성동구  11200  127.041059  37.551030
16   성북구  11290  127.017579  37.605702
17   송파구  11710  127.115295  37.505619
18   양천구  11470  126.855478  37.524789
19  영등포구  11560  126.910169  37.522308
20   용산구  11170  126.979907  37.531385
21   은평구  11380  126.927023  37.619211
22   종로구  11110  126.977321  37.594917
23    중구  11140  126.995968  37.560144
24   중랑구  11260  127.092880  37.597803

In [39]:
# csv 파일로 저장
result.to_csv('data/seoul_long_lat.csv', encoding='utf-8-sig', index=False)

# **경기**

### 시군구별 최종안전점검결과/준공후경과년수 평균

In [40]:
gyeonggi = pd.read_csv('data/g_map_data.csv')
gyeonggi.tail(3)

        교량명 시군구명 최종안전점검결과  준공후경과년수 시설물종별등급구분    교량시작점위도     교량시작점경도
5554  무지개다리  과천시        B       39         3  37.418700  127.026256
5555   원앙다리  과천시        B       39         3  37.428025  127.014776
5556  나들목다리  과천시        B       39         3  37.438942  127.009577

In [41]:
# 안전등급 매핑 딕셔너리 생성
safety_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5}
gyeonggi['safty'] = gyeonggi['최종안전점검결과'].map(safety_map)
gyeonggi

        교량명 시군구명 최종안전점검결과  준공후경과년수 시설물종별등급구분    교량시작점위도     교량시작점경도  safty
0       진위교  평택시        B       37         2  37.100957  127.064200      2
1       풍계교  이천시        B       27         3  37.133443  127.602141      2
2       태평교  여주시        B       32         3  37.200325  127.545522      2
3       장평교  이천시        B       30         2  37.225055  127.524158      2
4       풍계교  이천시        B       35         3  37.149231  127.626386      2
...     ...  ...      ...      ...       ...        ...         ...    ...
5552   산새다리  과천시        B       39         3  37.419885  127.024271      2
5553   들소다리  과천시        B       39         3  37.419038  127.025076      2
5554  무지개다리  과천시        B       39         3  37.418700  127.026256      2
5555   원앙다리  과천시        B       39         3  37.428025  127.014776      2
5556  나들목다리  과천시        B       39         3  37.438942  127.009577      2

[5557 rows x 8 columns]

In [42]:
g = gyeonggi[['교량명', '시군구명', '최종안전점검결과','safty', '준공후경과년수', '시설물종별등급구분', '교량시작점위도', '교량시작점경도']]
g

        교량명 시군구명 최종안전점검결과  safty  준공후경과년수 시설물종별등급구분    교량시작점위도     교량시작점경도
0       진위교  평택시        B      2       37         2  37.100957  127.064200
1       풍계교  이천시        B      2       27         3  37.133443  127.602141
2       태평교  여주시        B      2       32         3  37.200325  127.545522
3       장평교  이천시        B      2       30         2  37.225055  127.524158
4       풍계교  이천시        B      2       35         3  37.149231  127.626386
...     ...  ...      ...    ...      ...       ...        ...         ...
5552   산새다리  과천시        B      2       39         3  37.419885  127.024271
5553   들소다리  과천시        B      2       39         3  37.419038  127.025076
5554  무지개다리  과천시        B      2       39         3  37.418700  127.026256
5555   원앙다리  과천시        B      2       39         3  37.428025  127.014776
5556  나들목다리  과천시        B      2       39         3  37.438942  127.009577

[5557 rows x 8 columns]

In [43]:
unique_values = g['시군구명'].unique()
print(unique_values)

['평택시' '이천시' '여주시' '안성시' '김포시' '광주시' '화성시' '용인시 처인구' '용인시 기흥구' '파주시' '연천군'
 '양평군' '가평군' '포천시' '남양주시' '양주시' '동두천시' '의정부시' '하남시' '고양시 덕양구' '구리시' '광명시'
 '고양시 일산서구' '과천시' '수원시 권선구' '의왕시' '수원시 장안구' '시흥시' '수원시 팔달구' '수원시 영통구'
 '용인시 수지구' '성남시 수정구' '성남시 중원구' '성남시 분당구' '안양시 만안구' '안양시 동안구' '부천시'
 '안산시 단원구' '안산시 상록구' '군포시' '고양시 일산동구' '오산시' '부천시 오정구' '부천시 원미구' '부천시 소사구'
 '용인시' '화성군' '안성군' '이천군' '광주군' '포천군' '여주군']

In [44]:
# 시군구코드 추가
local_code = {'평택시':41220, '이천시':41500, '여주시':41730, '안성시':41550, '김포시':41570 , '광주시':41610, '화성시':41590,
              '용인시 처인구':41461, '용인시 기흥구':41463, '파주시':41480, '연천군':41800, '양평군':41830,
              '가평군':41820, '포천시':41650, '남양주시':41360, '양주시':41630, '동두천시':41250, '의정부시':41150,
              '하남시':41450, '고양시 덕양구':41281, '구리시':41310, '광명시':41210, '고양시 일산서구':41287,
              '과천시':41290, '수원시 권선구':41113, '의왕시':41430, '수원시 장안구': 41111, '여주군':41730,
              '수원시 팔달구':41115, '수원시 영통구':41117, '용인시 수지구':41465, '성남시 수정구':41131,
              '성남시 중원구':41133, '성남시 분당구':41135, '안양시 만안구':41171, '안양시 동안구':41173,
              '부천시':41190, '안산시 단원구':41273, '안산시 상록구':41271, '군포시':41410, '고양시 일산동구':41285,
              '오산시':41370, '부천시 오정구':41199, '부천시 원미구':41195, '부천시 소사구':41197, '용인시':41460,
              '화성군':41750, '안성군':41550, '이천군':41840, '광주군':41790, '포천군':41810, '시흥시':41390}
g['id'] = g['시군구명'].map(local_code)
g

C:\Users\82109\AppData\Local\Temp\ipykernel_29516\3601945113.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g['id'] = g['시군구명'].map(local_code)

,교량명,시군구명,최종안전점검결과,safty,준공후경과년수,시설물종별등급구분,교량시작점위도,교량시작점경도,id
0,진위교,평택시,B,2,37,2,37.100957,127.064200,41220
1,풍계교,이천시,B,2,27,3,37.133443,127.602141,41500
2,태평교,여주시,B,2,32,3,37.200325,127.545522,41730
3,장평교,이천시,B,2,30,2,37.225055,127.524158,41500
4,풍계교,이천시,B,2,35,3,37.149231,127.626386,41500
...,...,...,...,...,...,...,...,...,...
5552,산새다리,과천시,B,2,39,3,37.419885,127.024271,41290
5553,들소다리,과천시,B,2,39,3,37.419038,127.025076,41290
5554,무지개다리,과천시,B,2,39,3,37.418700,127.026256,41290
5555,원앙다리,과천시,B,2,39,3,37.428025,127.014776,41290
5556,나들목다리,과천시,B,2,39,3,37.438942,127.009577,41290

In [45]:
g = g[['교량명', '시군구명', 'id', '최종안전점검결과','safty', '준공후경과년수', '시설물종별등급구분', '교량시작점위도', '교량시작점경도']]
g

,교량명,시군구명,id,최종안전점검결과,safty,준공후경과년수,시설물종별등급구분,교량시작점위도,교량시작점경도
0,진위교,평택시,41220,B,2,37,2,37.100957,127.064200
1,풍계교,이천시,41500,B,2,27,3,37.133443,127.602141
2,태평교,여주시,41730,B,2,32,3,37.200325,127.545522
3,장평교,이천시,41500,B,2,30,2,37.225055,127.524158
4,풍계교,이천시,41500,B,2,35,3,37.149231,127.626386
...,...,...,...,...,...,...,...,...,...
5552,산새다리,과천시,41290,B,2,39,3,37.419885,127.024271
5553,들소다리,과천시,41290,B,2,39,3,37.419038,127.025076
5554,무지개다리,과천시,41290,B,2,39,3,37.418700,127.026256
5555,원앙다리,과천시,41290,B,2,39,3,37.428025,127.014776
5556,나들목다리,과천시,41290,B,2,39,3,37.438942,127.009577

In [46]:
result = g.groupby('시군구명').agg({'safty': 'mean', '준공후경과년수': 'mean'}).reset_index()
result.columns = ['시군구명', 'mean_safty', 'mean_after']

# 시군구코드 추가
local_code = {'평택시':41220, '이천시':41500, '여주시':41670, '안성시':41550, '김포시':41570 , '광주시':41610, '화성시':41590,
              '용인시 처인구':41461, '용인시 기흥구':41463, '파주시':41480, '연천군':41800, '양평군':41830,
              '가평군':41820, '포천시':41650, '남양주시':41360, '양주시':41630, '동두천시':41250, '의정부시':41150,
              '하남시':41450, '고양시 덕양구':41281, '구리시':41310, '광명시':41210, '고양시 일산서구':41287,
              '과천시':41290, '수원시 권선구':41113, '의왕시':41430, '수원시 장안구': 41111, '여주군':41670,
              '수원시 팔달구':41115, '수원시 영통구':41117, '용인시 수지구':41465, '성남시 수정구':41131,
              '성남시 중원구':41133, '성남시 분당구':41135, '안양시 만안구':41171, '안양시 동안구':41173,
              '부천시':41190, '안산시 단원구':41273, '안산시 상록구':41271, '군포시':41410, '고양시 일산동구':41285,
              '오산시':41370, '부천시 오정구':41199, '부천시 원미구':41195, '부천시 소사구':41197, '용인시':41460,
              '화성군':41590, '안성군':41550, '이천군':41840, '광주군':41790, '포천군':41810, '시흥시':41390}
result['id'] = result['시군구명'].map(local_code)

result['mean_safty'] = round(result['mean_safty'], 1)
result['mean_after'] = round(result['mean_after'], 1)
result = result[['시군구명', 'id', 'mean_safty', 'mean_after']]
result

        시군구명     id  mean_safty  mean_after
0        가평군  41820         2.2        22.5
1    고양시 덕양구  41281         2.1        17.4
2   고양시 일산동구  41285         2.4        23.1
3   고양시 일산서구  41287         2.1        19.0
4        과천시  41290         2.1        32.4
5        광명시  41210         1.8        20.4
6        광주군  41790         1.6        24.8
7        광주시  41610         1.9        22.1
8        구리시  41310         2.0        19.3
9        군포시  41410         2.1        24.0
10       김포시  41570         2.1        17.6
11      남양주시  41360         2.0        19.1
12      동두천시  41250         2.0        15.2
13       부천시  41190         2.4        24.1
14   부천시 소사구  41197         2.0        25.0
15   부천시 오정구  41199         2.0        31.0
16   부천시 원미구  41195         2.0        26.5
17   성남시 분당구  41135         2.1        25.0
18   성남시 수정구  41131         2.2        24.5
19   성남시 중원구  41133         2.3        21.0
20   수원시 권선구  41113         2.0        22.6
21   수원시 영통구  41117         1.9        15.6
22   수원시 장안구  41111         2.1        24.3
23   수원시 팔달구  41115         2.1        24.2
24       시흥시  41390         1.9        18.5
25   안산시 단원구  41273         1.9        23.1
26   안산시 상록구  41271         2.0        24.5
27       안성군  41550         2.0        21.0
28       안성시  41550         2.0        20.6
29   안양시 동안구  41173         2.1        25.4
30   안양시 만안구  41171         2.0        21.0
31       양주시  41630         2.0        17.8
32       양평군  41830         2.1        22.0
33       여주군  41670         2.0        18.3
34       여주시  41670         2.0        17.9
35       연천군  41800         2.0        17.9
36       오산시  41370         2.0        22.6
37       용인시  41460         2.0        18.4
38   용인시 기흥구  41463         2.0        21.5
39   용인시 수지구  41465         2.0        20.9
40   용인시 처인구  41461         2.1        21.3
41       의왕시  41430         2.0        23.0
42      의정부시  41150         2.0        12.5
43       이천군  41840         1.7        15.4
44       이천시  41500         1.8        20.4
45       파주시  41480         2.1        19.0
46       평택시  41220         1.9        20.6
47       포천군  41810         1.0         6.0
48       포천시  41650         1.9        15.4
49       하남시  41450         1.9        25.5
50       화성군  41590         2.0        13.0
51       화성시  41590         1.8        15.8

In [47]:
r = result[~result['시군구명'].isin(['여주군', '안성군', '광주군', '이천군', '화성군', '부천시 소사구',
                                    '부천시 오정구', '부천시 원미구', '포천군'])].reset_index(drop=True)
r

        시군구명     id  mean_safty  mean_after
0        가평군  41820         2.2        22.5
1    고양시 덕양구  41281         2.1        17.4
2   고양시 일산동구  41285         2.4        23.1
3   고양시 일산서구  41287         2.1        19.0
4        과천시  41290         2.1        32.4
5        광명시  41210         1.8        20.4
6        광주시  41610         1.9        22.1
7        구리시  41310         2.0        19.3
8        군포시  41410         2.1        24.0
9        김포시  41570         2.1        17.6
10      남양주시  41360         2.0        19.1
11      동두천시  41250         2.0        15.2
12       부천시  41190         2.4        24.1
13   성남시 분당구  41135         2.1        25.0
14   성남시 수정구  41131         2.2        24.5
15   성남시 중원구  41133         2.3        21.0
16   수원시 권선구  41113         2.0        22.6
17   수원시 영통구  41117         1.9        15.6
18   수원시 장안구  41111         2.1        24.3
19   수원시 팔달구  41115         2.1        24.2
20       시흥시  41390         1.9        18.5
21   안산시 단원구  41273         1.9        23.1
22   안산시 상록구  41271         2.0        24.5
23       안성시  41550         2.0        20.6
24   안양시 동안구  41173         2.1        25.4
25   안양시 만안구  41171         2.0        21.0
26       양주시  41630         2.0        17.8
27       양평군  41830         2.1        22.0
28       여주시  41670         2.0        17.9
29       연천군  41800         2.0        17.9
30       오산시  41370         2.0        22.6
31       용인시  41460         2.0        18.4
32   용인시 기흥구  41463         2.0        21.5
33   용인시 수지구  41465         2.0        20.9
34   용인시 처인구  41461         2.1        21.3
35       의왕시  41430         2.0        23.0
36      의정부시  41150         2.0        12.5
37       이천시  41500         1.8        20.4
38       파주시  41480         2.1        19.0
39       평택시  41220         1.9        20.6
40       포천시  41650         1.9        15.4
41       하남시  41450         1.9        25.5
42       화성시  41590         1.8        15.8

In [48]:
r.loc[r['시군구명'] == '부천시', ['mean_safty', 'mean_after']] = [2.1, 26.7]
r

        시군구명     id  mean_safty  mean_after
0        가평군  41820         2.2        22.5
1    고양시 덕양구  41281         2.1        17.4
2   고양시 일산동구  41285         2.4        23.1
3   고양시 일산서구  41287         2.1        19.0
4        과천시  41290         2.1        32.4
5        광명시  41210         1.8        20.4
6        광주시  41610         1.9        22.1
7        구리시  41310         2.0        19.3
8        군포시  41410         2.1        24.0
9        김포시  41570         2.1        17.6
10      남양주시  41360         2.0        19.1
11      동두천시  41250         2.0        15.2
12       부천시  41190         2.1        26.7
13   성남시 분당구  41135         2.1        25.0
14   성남시 수정구  41131         2.2        24.5
15   성남시 중원구  41133         2.3        21.0
16   수원시 권선구  41113         2.0        22.6
17   수원시 영통구  41117         1.9        15.6
18   수원시 장안구  41111         2.1        24.3
19   수원시 팔달구  41115         2.1        24.2
20       시흥시  41390         1.9        18.5
21   안산시 단원구  41273         1.9        23.1
22   안산시 상록구  41271         2.0        24.5
23       안성시  41550         2.0        20.6
24   안양시 동안구  41173         2.1        25.4
25   안양시 만안구  41171         2.0        21.0
26       양주시  41630         2.0        17.8
27       양평군  41830         2.1        22.0
28       여주시  41670         2.0        17.9
29       연천군  41800         2.0        17.9
30       오산시  41370         2.0        22.6
31       용인시  41460         2.0        18.4
32   용인시 기흥구  41463         2.0        21.5
33   용인시 수지구  41465         2.0        20.9
34   용인시 처인구  41461         2.1        21.3
35       의왕시  41430         2.0        23.0
36      의정부시  41150         2.0        12.5
37       이천시  41500         1.8        20.4
38       파주시  41480         2.1        19.0
39       평택시  41220         1.9        20.6
40       포천시  41650         1.9        15.4
41       하남시  41450         1.9        25.5
42       화성시  41590         1.8        15.8

In [49]:
# csv 파일로 저장
r.to_csv('data/g_r_mean4.csv', encoding='utf-8-sig', index=False)

### 시군구별 위도/경도

In [50]:
r['시군구명'] = r['시군구명'].replace('고양시 일산동구', '고양시')
r['시군구명'] = r['시군구명'].replace('성남시 수정구', '성남시')
r['시군구명'] = r['시군구명'].replace('수원시 장안구', '수원시')
r['시군구명'] = r['시군구명'].replace('안산시 상록구', '안산시')
r['시군구명'] = r['시군구명'].replace('안양시 동안구', '안양시')
r['시군구명'] = r['시군구명'].replace('용인시 처인구', '용인시')
r

        시군구명     id  mean_safty  mean_after
0        가평군  41820         2.2        22.5
1    고양시 덕양구  41281         2.1        17.4
2        고양시  41285         2.4        23.1
3   고양시 일산서구  41287         2.1        19.0
4        과천시  41290         2.1        32.4
5        광명시  41210         1.8        20.4
6        광주시  41610         1.9        22.1
7        구리시  41310         2.0        19.3
8        군포시  41410         2.1        24.0
9        김포시  41570         2.1        17.6
10      남양주시  41360         2.0        19.1
11      동두천시  41250         2.0        15.2
12       부천시  41190         2.1        26.7
13   성남시 분당구  41135         2.1        25.0
14       성남시  41131         2.2        24.5
15   성남시 중원구  41133         2.3        21.0
16   수원시 권선구  41113         2.0        22.6
17   수원시 영통구  41117         1.9        15.6
18       수원시  41111         2.1        24.3
19   수원시 팔달구  41115         2.1        24.2
20       시흥시  41390         1.9        18.5
21   안산시 단원구  41273         1.9        23.1
22       안산시  41271         2.0        24.5
23       안성시  41550         2.0        20.6
24       안양시  41173         2.1        25.4
25   안양시 만안구  41171         2.0        21.0
26       양주시  41630         2.0        17.8
27       양평군  41830         2.1        22.0
28       여주시  41670         2.0        17.9
29       연천군  41800         2.0        17.9
30       오산시  41370         2.0        22.6
31       용인시  41460         2.0        18.4
32   용인시 기흥구  41463         2.0        21.5
33   용인시 수지구  41465         2.0        20.9
34       용인시  41461         2.1        21.3
35       의왕시  41430         2.0        23.0
36      의정부시  41150         2.0        12.5
37       이천시  41500         1.8        20.4
38       파주시  41480         2.1        19.0
39       평택시  41220         1.9        20.6
40       포천시  41650         1.9        15.4
41       하남시  41450         1.9        25.5
42       화성시  41590         1.8        15.8

In [51]:
r = r[~r['시군구명'].isin(['고양시 덕양구', '고양시 일산서구', '성남시 분당구', '성남시 중원구',
                                    '수원시 권선구', '수원시 영통구', '수원시 팔달구', '안산시 단원구',
                                   '안양시 만안구', '용인시 기흥구', '용인시 수지구'])].reset_index(drop=True)
r

    시군구명     id  mean_safty  mean_after
0    가평군  41820         2.2        22.5
1    고양시  41285         2.4        23.1
2    과천시  41290         2.1        32.4
3    광명시  41210         1.8        20.4
4    광주시  41610         1.9        22.1
5    구리시  41310         2.0        19.3
6    군포시  41410         2.1        24.0
7    김포시  41570         2.1        17.6
8   남양주시  41360         2.0        19.1
9   동두천시  41250         2.0        15.2
10   부천시  41190         2.1        26.7
11   성남시  41131         2.2        24.5
12   수원시  41111         2.1        24.3
13   시흥시  41390         1.9        18.5
14   안산시  41271         2.0        24.5
15   안성시  41550         2.0        20.6
16   안양시  41173         2.1        25.4
17   양주시  41630         2.0        17.8
18   양평군  41830         2.1        22.0
19   여주시  41670         2.0        17.9
20   연천군  41800         2.0        17.9
21   오산시  41370         2.0        22.6
22   용인시  41460         2.0        18.4
23   용인시  41461         2.1        21.3
24   의왕시  41430         2.0        23.0
25  의정부시  41150         2.0        12.5
26   이천시  41500         1.8        20.4
27   파주시  41480         2.1        19.0
28   평택시  41220         1.9        20.6
29   포천시  41650         1.9        15.4
30   하남시  41450         1.9        25.5
31   화성시  41590         1.8        15.8

In [52]:
r['시군구명'].unique()

array(['가평군', '고양시', '과천시', '광명시', '광주시', '구리시', '군포시', '김포시', '남양주시',
       '동두천시', '부천시', '성남시', '수원시', '시흥시', '안산시', '안성시', '안양시', '양주시',
       '양평군', '여주시', '연천군', '오산시', '용인시', '의왕시', '의정부시', '이천시', '파주시',
       '평택시', '포천시', '하남시', '화성시'], dtype=object)

In [53]:
# 경도 추가
local_long = {'가평군':127.5117778, '고양시':126.7770556,
              '과천시':126.9898, '광명시':126.8667083, '광주시':127.2577861,
              '구리시':127.1318639, '군포시':126.9375, '김포시':126.7177778, '남양주시':127.2186333, '동두천시':127.0626528,
              '부천시':126.766, '성남시':127.1477194,
              '수원시':127.0122222,
              '시흥시':126.8050778, '안산시':126.8468194,
              '안성시':127.2818444, '안양시':126.9533556,
              '양주시':127.0478194, '양평군':127.4898861,'여주시':127.6396222, '연천군':127.0770667,
              '오산시':127.0796417, '용인시':127.2038444,
              '의왕시':126.9703889, '의정부시':127.0358417,
              '이천시':127.4432194, '파주시':126.7819528, '평택시':127.1146556, '포천시':127.2024194,
              '하남시':127.217, '화성시':126.8335306}
r['long'] = r['시군구명'].map(local_long)
r

    시군구명     id  mean_safty  mean_after        long
0    가평군  41820         2.2        22.5  127.511778
1    고양시  41285         2.4        23.1  126.777056
2    과천시  41290         2.1        32.4  126.989800
3    광명시  41210         1.8        20.4  126.866708
4    광주시  41610         1.9        22.1  127.257786
5    구리시  41310         2.0        19.3  127.131864
6    군포시  41410         2.1        24.0  126.937500
7    김포시  41570         2.1        17.6  126.717778
8   남양주시  41360         2.0        19.1  127.218633
9   동두천시  41250         2.0        15.2  127.062653
10   부천시  41190         2.1        26.7  126.766000
11   성남시  41131         2.2        24.5  127.147719
12   수원시  41111         2.1        24.3  127.012222
13   시흥시  41390         1.9        18.5  126.805078
14   안산시  41271         2.0        24.5  126.846819
15   안성시  41550         2.0        20.6  127.281844
16   안양시  41173         2.1        25.4  126.953356
17   양주시  41630         2.0        17.8  127.047819
18   양평군  41830         2.1        22.0  127.489886
19   여주시  41670         2.0        17.9  127.639622
20   연천군  41800         2.0        17.9  127.077067
21   오산시  41370         2.0        22.6  127.079642
22   용인시  41460         2.0        18.4  127.203844
23   용인시  41461         2.1        21.3  127.203844
24   의왕시  41430         2.0        23.0  126.970389
25  의정부시  41150         2.0        12.5  127.035842
26   이천시  41500         1.8        20.4  127.443219
27   파주시  41480         2.1        19.0  126.781953
28   평택시  41220         1.9        20.6  127.114656
29   포천시  41650         1.9        15.4  127.202419
30   하남시  41450         1.9        25.5  127.217000
31   화성시  41590         1.8        15.8  126.833531

In [54]:
# 위도 추가
local_lat = {'가평군':37.82883056, '고양시':37.65590833,
              '과천시':37.42637222, '광명시':37.47575, '광주시':37.414505561,
              '구리시':37.591625, '군포시':37.35865833, '김포시':37.61245833, '남양주시':37.63317778, '동두천시':37.90091667,
              '부천시':37.5035917, '성남시':37.44749167,
              '수원시':37.30101111,
              '시흥시':37.37731944, '안산시':37.29851944,
              '안성시':37.005175, '안양시':37.3897,
              '양주시':37.78245, '양평군':37.48893611,'여주시':37.29535833, '연천군':38.09336389,
              '오산시':37.14691389, '용인시':37.23147778,
              '의왕시':37.34195, '의정부시':37.73528889,
              '이천시':37.27543611, '파주시':37.75708333, '평택시':36.98943889, '포천시':37.89215556,
              '하남시':37.53649722, '화성시':37.19681667}
r['lat'] = r['시군구명'].map(local_lat)
r

    시군구명     id  mean_safty  mean_after        long        lat
0    가평군  41820         2.2        22.5  127.511778  37.828831
1    고양시  41285         2.4        23.1  126.777056  37.655908
2    과천시  41290         2.1        32.4  126.989800  37.426372
3    광명시  41210         1.8        20.4  126.866708  37.475750
4    광주시  41610         1.9        22.1  127.257786  37.414506
5    구리시  41310         2.0        19.3  127.131864  37.591625
6    군포시  41410         2.1        24.0  126.937500  37.358658
7    김포시  41570         2.1        17.6  126.717778  37.612458
8   남양주시  41360         2.0        19.1  127.218633  37.633178
9   동두천시  41250         2.0        15.2  127.062653  37.900917
10   부천시  41190         2.1        26.7  126.766000  37.503592
11   성남시  41131         2.2        24.5  127.147719  37.447492
12   수원시  41111         2.1        24.3  127.012222  37.301011
13   시흥시  41390         1.9        18.5  126.805078  37.377319
14   안산시  41271         2.0        24.5  126.846819  37.298519
15   안성시  41550         2.0        20.6  127.281844  37.005175
16   안양시  41173         2.1        25.4  126.953356  37.389700
17   양주시  41630         2.0        17.8  127.047819  37.782450
18   양평군  41830         2.1        22.0  127.489886  37.488936
19   여주시  41670         2.0        17.9  127.639622  37.295358
20   연천군  41800         2.0        17.9  127.077067  38.093364
21   오산시  41370         2.0        22.6  127.079642  37.146914
22   용인시  41460         2.0        18.4  127.203844  37.231478
23   용인시  41461         2.1        21.3  127.203844  37.231478
24   의왕시  41430         2.0        23.0  126.970389  37.341950
25  의정부시  41150         2.0        12.5  127.035842  37.735289
26   이천시  41500         1.8        20.4  127.443219  37.275436
27   파주시  41480         2.1        19.0  126.781953  37.757083
28   평택시  41220         1.9        20.6  127.114656  36.989439
29   포천시  41650         1.9        15.4  127.202419  37.892156
30   하남시  41450         1.9        25.5  127.217000  37.536497
31   화성시  41590         1.8        15.8  126.833531  37.196817

In [55]:
r = r[['시군구명', 'id', 'long', 'lat']]
r

    시군구명     id        long        lat
0    가평군  41820  127.511778  37.828831
1    고양시  41285  126.777056  37.655908
2    과천시  41290  126.989800  37.426372
3    광명시  41210  126.866708  37.475750
4    광주시  41610  127.257786  37.414506
5    구리시  41310  127.131864  37.591625
6    군포시  41410  126.937500  37.358658
7    김포시  41570  126.717778  37.612458
8   남양주시  41360  127.218633  37.633178
9   동두천시  41250  127.062653  37.900917
10   부천시  41190  126.766000  37.503592
11   성남시  41131  127.147719  37.447492
12   수원시  41111  127.012222  37.301011
13   시흥시  41390  126.805078  37.377319
14   안산시  41271  126.846819  37.298519
15   안성시  41550  127.281844  37.005175
16   안양시  41173  126.953356  37.389700
17   양주시  41630  127.047819  37.782450
18   양평군  41830  127.489886  37.488936
19   여주시  41670  127.639622  37.295358
20   연천군  41800  127.077067  38.093364
21   오산시  41370  127.079642  37.146914
22   용인시  41460  127.203844  37.231478
23   용인시  41461  127.203844  37.231478
24   의왕시  41430  126.970389  37.341950
25  의정부시  41150  127.035842  37.735289
26   이천시  41500  127.443219  37.275436
27   파주시  41480  126.781953  37.757083
28   평택시  41220  127.114656  36.989439
29   포천시  41650  127.202419  37.892156
30   하남시  41450  127.217000  37.536497
31   화성시  41590  126.833531  37.196817

In [56]:
# csv 파일로 저장
r.to_csv('data/gyeonggi_long_lat.csv', encoding='utf-8-sig', index=False)